### ISSUE TITLE
Password characters are limited or incorrect

### ISSUE THREAD

**Issue by Shawn-Jones-7** [wibus-wee/InjectGUI#14]
My password contains "," and when I am asked to enter the password, no matter how I switch the input, it is always wrong, which forces me to change my password.

**Comment by wibus-wee** [comment]
fixed

**Comment by Shawn-Jones-7** [comment]
> fixed

I conducted another test and the issue remained unchanged. Possibly, my previous formulation was incorrect. Specifically, it was "\ or | or、 " precisely above the Enter key.

**Comment by wibus-wee** [comment]
OK, I'll test it again.

**Comment by RayPS** [comment]
Same issue here, my password contains `;` and `'`

**Comment by wibus-wee** [comment]
Can you test whether the artifact is effective? 

https://github.com/wibus-wee/InjectGUI/actions/runs/10416144750

**Comment by RayPS** [comment]
> Can you test whether the artifact is effective?
> 
> https://github.com/wibus-wee/InjectGUI/actions/runs/10416144750

Thank you for investigating the issue, but the problem still persists in this artifact.

**Comment by RayPS** [comment]
Also new to Swift but I've personally made these changes to avoid dealing with special characters:

`func checkAndSavePassword()`:
```diff
-        executor.password = password
+        executor.password = password.encode()
```
`func runAdminCommand()`:
```diff
-            task.arguments = ["-c", "echo \(self.password) | sudo -S bash -c \"\(escapedCommand)\""]
+            task.arguments = ["-c", "echo \(self.password) | base64 --decode | sudo -S bash -c \"\(escapedCommand)\""]

```

`extension String {}`:
```swift
    func encode() -> String {
        if let data = self.data(using: .utf8) {
            return data.base64EncodedString()
        }
        return ""
    }
```

Hope that helps.

**Comment by wibus-wee** [comment]
@RayPS Thanks for the code!
